name: Moodle CI (light)

on:
  workflow_dispatch:
    inputs:
      moodle_branch:
        description: 'Moodle branch'
        required: true
        default: 'MOODLE_500_STABLE'
      php:
        description: 'PHP version'
        required: true
        default: '8.2'

jobs:
  static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with: { node-version: '22' }

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php }}
          extensions: zip, gd, soap, xmlrpc, mysqli, pgsql
          ini-values: max_input_vars=5000
          coverage: none

      - name: Install moodle-plugin-ci
        run: |
          composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^4
          echo "$PWD/ci/bin" >> $GITHUB_PATH

      - name: Init moodle-plugin-ci (no DB)
        run: moodle-plugin-ci install --branch ${{ inputs.moodle_branch }} --pluginsource plugin

      - name: PHP Lint
        run: moodle-plugin-ci phplint

      - name: Code checker
        run: moodle-plugin-ci codechecker --max-warnings=-1

      - name: Validate plugin
        run: moodle-plugin-ci validate

      - name: Grunt (JS/CSS)
        run: moodle-plugin-ci grunt
